apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextwork-rag-api
  template:
    metadata:
      labels:
        app: nextwork-rag-api
    spec:
      containers:
      - name: rag-api-container
        image: nextwork-rag-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_HOST
          value: "host.docker.internal:11434"
